### ISSUE TITLE
data

### ISSUE THREAD

**Issue by bigdimboom** [JonathonLuiten/Dynamic3DGaussians#1]
May I ask for data you captured. I want to compare the technique of yours with other reconstruction methods.

**Comment by bigdimboom** [comment]
never mind, I saw you have mentioned what dataset you used. For those who have the same interests: http://domedb.perception.cs.cmu.edu/

**Comment by JonathonLuiten** [comment]
Yes the raw data can be downloaded from the cmu panoptic website. However this data requires ALOT of processing until it is useful for this task. I will release all the preprocessed data and code and everything as soon as it is ready. Aiming for Sep 17, but could be as late as Oct 1.

**Comment by niopeng** [comment]
Hi,

I'm also interested in this. Would it be possible to release the preprocessed data anytime soon?

Thanks

**Comment by JonathonLuiten** [comment]
Yup trying to do so asap

**Comment by JonathonLuiten** [comment]
it's released
