### ISSUE TITLE
Request for uncleaned data processing code

### ISSUE THREAD

**Issue by anhtuanhsgs** [JonathonLuiten/Dynamic3DGaussians#12]
Hi, thanks for the amazing work. Can you please share the uncleaned processing code for the data if possible? 

We have been trying to get the right camera pose from the raw CMU data (their caliberation json file) to work with Gaussian Splatting but this seems tricky.

**Comment by JonathonLuiten** [comment]
Yeah I plan on releasing this as soon as I find time to clean it up.

An honest estimate for when I find such a time might be around xmas though.

I feel your pain though, it was a real nightmare to deal with for me too...

**Comment by JonathonLuiten** [comment]
but I can drop a few lines from the code here for the camera pose which should help you:

```
calib = json.load(open(f"{base}/{scene}/calibration_{scene}.json", 'r'))['cameras']
calib = [x for x in calib if x['type']=='hd']
w2cs = [np.concatenate((np.concatenate((x['R'], np.array(x['t'])/100), 1), np.eye(4)[3:]), 0) for x in calib]
```

I think that's all you need???

Also note the data is hard (weird) to sync across cameras and also to undistort the distortion in the images too though, so this might not actually be all you need.

Will close this for now, and hopefully have been helpful enough until I find time to clean up and release the pre-processing code...
