### ISSUE TITLE
Data preparation (Nov 1 estimated release)

### ISSUE THREAD

**Issue by atonalfreerider** [JonathonLuiten/Dynamic3DGaussians#13]
First of all, thank you, and congratulations. Rarely do I pull one of these projects onto my machine, and it just WORKS. I was up and running in almost no time, with your prepared visualizations. I was shocked at how clean the code is as well. I'm also running on Windows. Thank you for making it work here too (I'm using MiniConda and MVSC x64/x86 build tools for the visualizer and CUDA 11.7).

Question about the data pipeline. I see in the readme that you are estimating a release for the data preparation code around Nov 1. A few questions ahead of this. If I have **two videos** of a subject shot at different angles (.mp4) and I want to create a dynamic 3d gaussian out of these videos, will the data preparation script take these videos and do the following?:
- segments them
- calculate the camera positions (similar to how Colmap would place cameras)
- generate the necessary `train_meta.json` and the `ims` and `seg` folders and polulate them
- create the `init_pt_cld.npz` file

I'm wondering if there is any additional hacking I need to do ahead of that time to prepare the data. Thank you again.

**Comment by JonathonLuiten** [comment]
So I only ever tried this on data recorded with 10-27 cameras. I have no idea how well it will work with 2. 

I'm also not sure the data preparation code will particularly help you here either. Mostly it will be about dealing with the intricacies of the CMU panoptic dataset. 

But in general your steps your laid out are correct. And once you know the format (e.g. from the example data I supplied), then it should be relatively easy to get custom data in the right format.

Getting things to work well with only 2 cameras though... might be hard.

**Comment by AlanxChen** [comment]
@atonalfreerider Hello ,I was wondering if you have had the opportunity to try the results with 2 cameras, or even just a single camera setup. It would be great to hear about your experience with these configurations, if applicable.
