### ISSUE TITLE
Code  release

### ISSUE THREAD

**Issue by jb892** [JonathonLuiten/Dynamic3DGaussians#2]
Hi @JonathonLuiten, I'm eagerly following your project. Could you provide an estimated timeline for when the code might be released? Thank you for your hard work!

**Comment by JonathonLuiten** [comment]
Hey hey!!!

Thanks for your interest!

I’m trying to release it as soon as possible. This week I’m at ICCV so earliest will be Monday 9th, but there is still a bug I’m trying to fix (in the cleaned code, but not in the original code). As soon as I fix this bug I will upload the code. It’s hard to predict when this will be, but I hope as soon as possible.

**Comment by JonathonLuiten** [comment]
it's released
