### ISSUE TITLE
Implementation of 2D tracking

### ISSUE THREAD

**Issue by jasongzy** [JonathonLuiten/Dynamic3DGaussians#20]
Hi, thanks for your excellent work!

I'm pretty interested in the pixel-level 2D tracking application. According to the paper, after getting the depth values, we need to perform operations including "unprojection, the highest influence Gaussian determined, tracked and then projected into a new camera frame."

I understand that the evaluation code for tracking has not been released yet, but could you please provide some sample code for this part (or to be specific, the pixel-to-3D-Gaussian process)? That will really help me a lot!

Looking forward to your response, and again, thanks for the great job!

**Comment by JonathonLuiten** [comment]
The pixel to 3D Gaussian is the same as being used for the ‘median depth’ in the rasterisation code. Eg the median depth is the depth of the highest influence Gaussian. Hope this helps.

**Comment by jasongzy** [comment]
Thanks for your reply!

While the CUDA-based Renderer does produce the depth value, it does not return the index of that highest influence Gaussian.
For 2D tracking, I believe we'll have to keep track of that target Gaussian and re-project it to the image plane.

How do you complete this without the Gaussian index? Did you modify the CUDA code, or did I miss something?

**Comment by JonathonLuiten** [comment]
No didn't use the CUDA to get the index, although that would be a better way to do it.

After I got the median depth, that gives you a 3D point. Then you can calculate the influence of all the (nearby) gaussians on this 3D point and find the one with the highest influence.

**Comment by jasongzy** [comment]
Got it. Thanks!
