### ISSUE TITLE
How to do scene editing?

### ISSUE THREAD

**Issue by chiehwangs** [JonathonLuiten/Dynamic3DGaussians#21]
Great job!

 I'm very interested in the application related to scene editing. Could you provide a brief overview of how this is achieved?

best,
chieh

**Comment by JonathonLuiten** [comment]
The “compositional scenes” example is very easy. 

Points are labelled as FG or BG (the current code already does this). Then we can take only the FG points from dynamic scenes, combine them with the points of a new BG scene and move and rotate them around as desired.
