### ISSUE TITLE
Camera Coordinate System

### ISSUE THREAD

**Issue by luoxue-star** [JonathonLuiten/Dynamic3DGaussians#23]
Is the definition of the camera coordinate system in train_meta.json the same as that in Blender?

**Comment by JonathonLuiten** [comment]
My code uses the OpenCV camera co-ordinate system (same as COLMAP).

This is different to the blender / standard NeRF camera coordinate system.

The conversion code between the two can be found here: 
https://github.com/NVlabs/instant-ngp/blob/9f6ab886306ce1f9b359d3856e8a1907ce8b8c8b/scripts/colmap2nerf.py#L350

**Comment by tb2-sy** [comment]
> My code uses the OpenCV camera co-ordinate system (same as COLMAP).
> 
> This is different to the blender / standard NeRF camera coordinate system.
> 
> The conversion code between the two can be found here: https://github.com/NVlabs/instant-ngp/blob/9f6ab886306ce1f9b359d3856e8a1907ce8b8c8b/scripts/colmap2nerf.py#L350

Hi, thanks for your nice work! As you said above, you are using COLMAPs Coordinate system. What I don't understand is what is the function of opengl_proj, why not use ProjectionMatrix same as the original 3D gaussian splatting?
