### ISSUE TITLE
Weird result on custom dataset

### ISSUE THREAD

**Issue by aashutoshpy** [JonathonLuiten/Dynamic3DGaussians#27]
I prepared a custom dataset in necessary format and ran training script. The PSNR was only around 13, also the resulting gaussian is quite odd. I used 1 for the mask segmentation for all the points in initial point cloud.
![image](https://github.com/JonathonLuiten/Dynamic3DGaussians/assets/107194699/1a5de263-20b8-40f6-97ff-d87e3885710a)
Could you point out what could be the issue here?

**Comment by luoxue-star** [comment]
> I prepared a custom dataset in necessary format and ran training script. The PSNR was only around 13, also the resulting gaussian is quite odd. I used 1 for the mask segmentation for all the points in initial point cloud. ![image](https://private-user-images.githubusercontent.com/107194699/293447070-1a5de263-20b8-40f6-97ff-d87e3885710a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTE3OTYsIm5iZiI6MTcwNDE5MTQ5NiwicGF0aCI6Ii8xMDcxOTQ2OTkvMjkzNDQ3MDcwLTFhNWRlMjYzLTIwYjgtNDBmNi05N2ZmLWQ4N2UzODg1NzEwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMDMxMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjM0MmZlZTJiY2ZhZGYxZDk3N2E3MDhiMTYyZjNiZGM0YjM1NDlmMmJiMjBiOWRjMDA4ZDFkZGJmMjQ2YjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rJK9TZn_M0pt6Qwujczyvwooo-ju5Tz8hGj-fE0-dR0) Could you point out what could be the issue here?

@aashutoshpy Hi, I meet the same issue. Could you tell me how to solve it?

**Comment by williambittner1** [comment]
Downgrading from open3d version 0.17.0 to 1.16.0 solved the issue for me.
`pip install open3d==0.16.0`

**Comment by flow-specter** [comment]
hi, how do you prepare a custom dataset?
