### ISSUE TITLE
Why near camera rendering is bad?

### ISSUE THREAD

**Issue by SizheAn** [JonathonLuiten/Dynamic3DGaussians#3]
Congrats on your excellent work!

In Gaussian-Eye View: First-Person and Gaussian-Eye View: Object View these two videos in your [project page](https://dynamic3dgaussians.github.io/), I'm surprised that the near-field rendering from egocentric view is so bad, given promising quality in far-field rendering. Any specific reasons for this performance degradation?

![image](https://github.com/JonathonLuiten/Dynamic3DGaussians/assets/87412724/64b0ffed-c423-4e04-b1d4-9d6a0eb35383)
![image](https://github.com/JonathonLuiten/Dynamic3DGaussians/assets/87412724/c3db6e83-95ca-40c0-9f47-89f9ff29f7d0)

**Comment by JonathonLuiten** [comment]
Great question!!!

There are two reasons: 
1) Near plane clipping is removing some closer points so it seems like arms are “floating”. 

2) (main reason) the projection from 3D Gaussians to 2D Gaussians that is used for the rasterisation is an approximation (see Zwickler 2001). This approximation breaks down with objects really close to the camera and really off to the side with wide field of view. This is mostly what you are seeing here. 

I think there are some good fixes for this in the future!

**Comment by JonathonLuiten** [comment]
For an example of the near plane clipping effect, see here: 

https://twitter.com/the_ross_man/status/1709376582253518941
