### ISSUE TITLE
Preprocessed data request

### ISSUE THREAD

**Issue by niopeng** [JonathonLuiten/Dynamic3DGaussians#4]
Hi,

I am interested in the data that you mentioned. Is it possible to release the preprocessed data anytime soon?

Thanks!

**Comment by Yang-Xijie** [comment]
What do you mean by "preprocessed data"?

> It (MatrixCity) is built in the [City Sample project of Unreal Engine 5](https://www.unrealengine.com/marketplace/en-US/product/city-sample) with advanced graphic technologies which allows for the public release of rendered images.

The [City Sample project of Unreal Engine 5](https://www.unrealengine.com/marketplace/en-US/product/city-sample) might be what you want?

**Comment by JonathonLuiten** [comment]
Yup when the code is ready. Trying to prep is asap!

**Comment by JonathonLuiten** [comment]
it's released
