### ISSUE TITLE
fix params in Gaussians

### ISSUE THREAD

**Issue by cv-lab-x** [JonathonLuiten/Dynamic3DGaussians#5]
Hi, thanks for your great work，some questions about the fixed params in Gaussians,  why do you fix the size, opacity, color even using rgb instead of sh,  what's the insight?
are there anything other methods to solve the dynamic scenes novel view synthesis using 3d gaussians ?
@JonathonLuiten Looking forward to your reply, thanks!

**Comment by JonathonLuiten** [comment]
I turned the view dependent effects (spherical harmonics) off for simplicity. They can easily be turned on again if you wish. 

I’m not aware of any other work using Gaussians for dynamic novel view synthesis.
