### ISSUE TITLE
open3d=0.16.0 missing on Windows

### ISSUE THREAD

**Issue by andr3wmac** [JonathonLuiten/Dynamic3DGaussians#7]
> ResolvePackageNotFound:
>  - open3d=0.16.0

To get this working on Windows I had to remove `open3d=0.16.0` from environment.yml, run the installation, then manually do `pip install open3d==0.16.0` and then everything worked as expected.

**Comment by JonathonLuiten** [comment]
Interesting! Thanks for pointing it out!

PS the most recent version of O3D has a bug that stops the visualizer working, so it is important that it’s this version.

**Comment by catid** [comment]
Fixed here: https://github.com/JonathonLuiten/Dynamic3DGaussians/pull/10
